### ISSUE TITLE
cf-stub.html is unclear

### ISSUE THREAD

**Issue by trondhindenes** [cloudfoundry/docs-deploying-cf#159]
The following sections could use some clarification:

consul: The command doesnt work until `git submodule init && git submodule update` has been run on the `cf-release` repo
ccdb (and other db sections): No list of supported database types (`postgresql` is listed, but there's no list of other valid options)
jwt: The command `openssl rsa -in jwt-key.pem -pubout > key.pub` doesn't work by itself (as `jwt-key.pem` doesn't exist)
etcd: no instruction
generate_deployment_manifest: This is listed as an executable, when its in fact a script in the scripts directory. The cmd line should be expressed as `./scripts/generate_deployment_manifest` (this is corrected farther down the documentation, but imho the doc would be a lot clearer if the first reference to a command was correct.

**Comment by ljarzynski** [comment]
@trondhindenes Thanks for bringing these items to our attention!

@dsabeti - Would you mind providing input items above regarding consul, ccdb, jwt, and etcd? If you can provide the content/clarifications, I can add it to the doc!

**Comment by dsabeti** [comment]
Sure.

### `consul`
Running `./scripts/update` (which itself runs `submodule init` and `submodule update` is considered to be an important normal part of the workflow with cf-release. @ljarzynski, if you can think of a place to put this in the docs, it would definitely make things clearer for people.

### Databases
Since different teams manage the uses of each of these databases, you'll have to get input from them about which database types are allowed for each.
@zrob: Which databases types -- postgres, mysql, etc. -- are supported by the Cloud Controller for ccdb?
@sreetummidi: Which database types --postgres, mysql, etc. -- are supported by the UAA for uaadb?

### jwt
This is the second or third time that we've found that the documented `openssl` commands are no longer working for deploying the UAA. You can see some discussion about this in [a different github issue](https://github.com/cloudfoundry/cf-release/issues/1164). I think you can check progress on the work [here](https://github.com/cloudfoundry/uaa/issues/582).

@sreetummidi and @fhanik: Can you make sure that the appropriate documentation makes it to docs.cloudfoundry.com?

### etcd
@evanfarrar, it looks like the [docs](http://docs.cloudfoundry.org/deploying/aws/cf-stub.html) show etcd in the example stub, but there's no explanation in the table underneath for how to generate the various certificates. I'm pretty sure it's relatively simple (`./scriptes/generate-etcd-certs`), but could you or someone from the infrastructure team update this repo with a short explanation?

**Comment by ljarzynski** [comment]
@dsabeti Thanks very much for your response and pulling the right people into the convo!

**Comment by ljarzynski** [comment]
updates:

- Confirmed that supported CCDB types are mysql and postgres
