### ISSUE TITLE
generate-bosh-lite-dev-manifest needs to be updated to cli-v2

### ISSUE THREAD

**Issue by jtdice** [cloudfoundry/docs-deploying-cf#188]
Similar to issue [182](https://github.com/cloudfoundry/docs-deploying-cf/issues/182).  The "generate-bosh-lite-dev-manifest" as it still references cli-v1 commands - e.g. line 25/26 going to "bosh status" instead of "bosh env...".

**Comment by seviet** [comment]
hi @jtdice! Since this is a problem with the "generate-bosh-lite-dev-manifest" script, I recommend reporting this as an issue in the `cf-release` repo (https://github.com/cloudfoundry/cf-release). However, just to let you know that `cf-release` is soon to be deprecated in favor of `cf-deployment`. See http://docs.cloudfoundry.org/deploying/cf-release/
